### ISSUE TITLE
Add site: https://christianoliff.com/

### ISSUE THREAD

**Issue by coliff** [jmooring/hugo-sites#2]
### Site

https://christianoliff.com/

### Type

- [X] Blog
- [ ] Business
- [ ] CV/Resume
- [ ] Documentation
- [ ] Ecommerce
- [ ] Education
- [ ] Entertainment
- [ ] Event
- [ ] Government
- [ ] Healthcare
- [ ] Membership
- [ ] News
- [ ] Nonprofit
- [ ] Personal
- [ ] Portfolio
- [ ] Project
- [ ] Other

**Comment by jmooring** [comment]
Closed with https://github.com/jmooring/hugo-sites/commit/e152e4a21710bf895262696c0c46a587c8d1c22a
